# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:alpine

WORKDIR /app

# Copy package and lock files first
COPY package.json bun.lockb ./

# Install dependencies using bun
RUN bun install

# Copy the rest of the app
COPY . .

# Expose a port if needed, for now assuming MCP server uses stdio, no port needed

CMD ["bun", "run", "index.ts"]
